
version: 2

sources:
  - name: staging
    database: sigma-icon-447800-e1
    schema: homework_4_dataset
      # loaded_at_field: record_loaded_at
    tables:
      - name: greentrip_data
      - name: yellowtrip_data
         # freshness:
           # error_after: {count: 6, period: hour}
      - name: fhv2019_data


